# Generated by Django 2.2.1 on 2019-10-18 17:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='Не заполнено', max_length=1200)),
                ('image', models.ImageField(default='images/no-img.jpg', upload_to='images')),
                ('members', models.TextField(blank=True, default='', max_length=500)),
                ('urlVK', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Volonteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_registered', models.CharField(blank=True, max_length=1000)),
                ('karma', models.FloatField(default=0)),
                ('location', models.CharField(default='Не указан', max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('vorname', models.CharField(blank=True, max_length=20)),
                ('nachname', models.CharField(blank=True, max_length=50)),
                ('urlVK', models.CharField(blank=True, max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('allergy', models.TextField(blank=True, default='Не заполнено', max_length=500)),
                ('profile_image', models.ImageField(default='images/no-img.jpg', upload_to='images')),
                ('shelters', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
